export interface Pipeable {
  pipe<const A>(this: A): A;
  pipe<const A, const B = never>(this: A, ab: (_: A) => B): B;
  pipe<const A, const B = never, const C = never>(
    this: A,
    ab: (_: A) => B,
    bc: (_: B) => C,
  ): C;
  pipe<const A, const B = never, const C = never, const D = never>(
    this: A,
    ab: (_: A) => B,
    bc: (_: B) => C,
    cd: (_: C) => D,
  ): D;
  pipe<const A, const B = never, const C = never, const D = never, const E = never>(
    this: A,
    ab: (_: A) => B,
    bc: (_: B) => C,
    cd: (_: C) => D,
    de: (_: D) => E,
  ): E;
  pipe<const A, const B = never, const C = never, const D = never, const E = never, const F = never>(
    this: A,
    ab: (_: A) => B,
    bc: (_: B) => C,
    cd: (_: C) => D,
    de: (_: D) => E,
    ef: (_: E) => F,
  ): F;
  pipe<
    const A,
    const B = never,
    const C = never,
    const D = never,
    const E = never,
    const F = never,
    const G = never,
  >(
    this: A,
    ab: (_: A) => B,
    bc: (_: B) => C,
    cd: (_: C) => D,
    de: (_: D) => E,
    ef: (_: E) => F,
    fg: (_: F) => G,
  ): G;
  pipe<
    const A,
    const B = never,
    const C = never,
    const D = never,
    const E = never,
    const F = never,
    const G = never,
    const H = never,
  >(
    this: A,
    ab: (_: A) => B,
    bc: (_: B) => C,
    cd: (_: C) => D,
    de: (_: D) => E,
    ef: (_: E) => F,
    fg: (_: F) => G,
    gh: (_: G) => H,
  ): H;
  pipe<
    const A,
    const B = never,
    const C = never,
    const D = never,
    const E = never,
    const F = never,
    const G = never,
    const H = never,
    const I = never,
  >(
    this: A,
    ab: (_: A) => B,
    bc: (_: B) => C,
    cd: (_: C) => D,
    de: (_: D) => E,
    ef: (_: E) => F,
    fg: (_: F) => G,
    gh: (_: G) => H,
    hi: (_: H) => I,
  ): I;
  pipe<
    const A,
    const B = never,
    const C = never,
    const D = never,
    const E = never,
    const F = never,
    const G = never,
    const H = never,
    const I = never,
    const J = never,
  >(
    this: A,
    ab: (_: A) => B,
    bc: (_: B) => C,
    cd: (_: C) => D,
    de: (_: D) => E,
    ef: (_: E) => F,
    fg: (_: F) => G,
    gh: (_: G) => H,
    hi: (_: H) => I,
    ij: (_: I) => J,
  ): J;
  pipe<
    const A,
    const B = never,
    const C = never,
    const D = never,
    const E = never,
    const F = never,
    const G = never,
    const H = never,
    const I = never,
    const J = never,
    const K = never,
  >(
    this: A,
    ab: (_: A) => B,
    bc: (_: B) => C,
    cd: (_: C) => D,
    de: (_: D) => E,
    ef: (_: E) => F,
    fg: (_: F) => G,
    gh: (_: G) => H,
    hi: (_: H) => I,
    ij: (_: I) => J,
    jk: (_: J) => K,
  ): K;
  pipe<
    const A,
    const B = never,
    const C = never,
    const D = never,
    const E = never,
    const F = never,
    const G = never,
    const H = never,
    const I = never,
    const J = never,
    const K = never,
    const L = never,
  >(
    this: A,
    ab: (_: A) => B,
    bc: (_: B) => C,
    cd: (_: C) => D,
    de: (_: D) => E,
    ef: (_: E) => F,
    fg: (_: F) => G,
    gh: (_: G) => H,
    hi: (_: H) => I,
    ij: (_: I) => J,
    jk: (_: J) => K,
    kl: (_: K) => L,
  ): L;
  pipe<
    const A,
    const B = never,
    const C = never,
    const D = never,
    const E = never,
    const F = never,
    const G = never,
    const H = never,
    const I = never,
    const J = never,
    const K = never,
    const L = never,
    const M = never,
  >(
    this: A,
    ab: (_: A) => B,
    bc: (_: B) => C,
    cd: (_: C) => D,
    de: (_: D) => E,
    ef: (_: E) => F,
    fg: (_: F) => G,
    gh: (_: G) => H,
    hi: (_: H) => I,
    ij: (_: I) => J,
    jk: (_: J) => K,
    kl: (_: K) => L,
    lm: (_: L) => M,
  ): M;
  pipe<
    const A,
    const B = never,
    const C = never,
    const D = never,
    const E = never,
    const F = never,
    const G = never,
    const H = never,
    const I = never,
    const J = never,
    const K = never,
    const L = never,
    const M = never,
    const N = never,
  >(
    this: A,
    ab: (_: A) => B,
    bc: (_: B) => C,
    cd: (_: C) => D,
    de: (_: D) => E,
    ef: (_: E) => F,
    fg: (_: F) => G,
    gh: (_: G) => H,
    hi: (_: H) => I,
    ij: (_: I) => J,
    jk: (_: J) => K,
    kl: (_: K) => L,
    lm: (_: L) => M,
    mn: (_: M) => N,
  ): N;
  pipe<
    const A,
    const B = never,
    const C = never,
    const D = never,
    const E = never,
    const F = never,
    const G = never,
    const H = never,
    const I = never,
    const J = never,
    const K = never,
    const L = never,
    const M = never,
    const N = never,
    const O = never,
  >(
    this: A,
    ab: (_: A) => B,
    bc: (_: B) => C,
    cd: (_: C) => D,
    de: (_: D) => E,
    ef: (_: E) => F,
    fg: (_: F) => G,
    gh: (_: G) => H,
    hi: (_: H) => I,
    ij: (_: I) => J,
    jk: (_: J) => K,
    kl: (_: K) => L,
    lm: (_: L) => M,
    mn: (_: M) => N,
    no: (_: N) => O,
  ): O;
  pipe<
    const A,
    const B = never,
    const C = never,
    const D = never,
    const E = never,
    const F = never,
    const G = never,
    const H = never,
    const I = never,
    const J = never,
    const K = never,
    const L = never,
    const M = never,
    const N = never,
    const O = never,
    const P = never,
  >(
    this: A,
    ab: (_: A) => B,
    bc: (_: B) => C,
    cd: (_: C) => D,
    de: (_: D) => E,
    ef: (_: E) => F,
    fg: (_: F) => G,
    gh: (_: G) => H,
    hi: (_: H) => I,
    ij: (_: I) => J,
    jk: (_: J) => K,
    kl: (_: K) => L,
    lm: (_: L) => M,
    mn: (_: M) => N,
    no: (_: N) => O,
    op: (_: O) => P,
  ): P;
  pipe<
    const A,
    const B = never,
    const C = never,
    const D = never,
    const E = never,
    const F = never,
    const G = never,
    const H = never,
    const I = never,
    const J = never,
    const K = never,
    const L = never,
    const M = never,
    const N = never,
    const O = never,
    const P = never,
    const Q = never,
  >(
    this: A,
    ab: (_: A) => B,
    bc: (_: B) => C,
    cd: (_: C) => D,
    de: (_: D) => E,
    ef: (_: E) => F,
    fg: (_: F) => G,
    gh: (_: G) => H,
    hi: (_: H) => I,
    ij: (_: I) => J,
    jk: (_: J) => K,
    kl: (_: K) => L,
    lm: (_: L) => M,
    mn: (_: M) => N,
    no: (_: N) => O,
    op: (_: O) => P,
    pq: (_: P) => Q,
  ): Q;
  pipe<
    const A,
    const B = never,
    const C = never,
    const D = never,
    const E = never,
    const F = never,
    const G = never,
    const H = never,
    const I = never,
    const J = never,
    const K = never,
    const L = never,
    const M = never,
    const N = never,
    const O = never,
    const P = never,
    const Q = never,
    const R = never,
  >(
    this: A,
    ab: (_: A) => B,
    bc: (_: B) => C,
    cd: (_: C) => D,
    de: (_: D) => E,
    ef: (_: E) => F,
    fg: (_: F) => G,
    gh: (_: G) => H,
    hi: (_: H) => I,
    ij: (_: I) => J,
    jk: (_: J) => K,
    kl: (_: K) => L,
    lm: (_: L) => M,
    mn: (_: M) => N,
    no: (_: N) => O,
    op: (_: O) => P,
    pq: (_: P) => Q,
    qr: (_: Q) => R,
  ): R;
  pipe<
    const A,
    const B = never,
    const C = never,
    const D = never,
    const E = never,
    const F = never,
    const G = never,
    const H = never,
    const I = never,
    const J = never,
    const K = never,
    const L = never,
    const M = never,
    const N = never,
    const O = never,
    const P = never,
    const Q = never,
    const R = never,
    const S = never,
  >(
    this: A,
    ab: (_: A) => B,
    bc: (_: B) => C,
    cd: (_: C) => D,
    de: (_: D) => E,
    ef: (_: E) => F,
    fg: (_: F) => G,
    gh: (_: G) => H,
    hi: (_: H) => I,
    ij: (_: I) => J,
    jk: (_: J) => K,
    kl: (_: K) => L,
    lm: (_: L) => M,
    mn: (_: M) => N,
    no: (_: N) => O,
    op: (_: O) => P,
    pq: (_: P) => Q,
    qr: (_: Q) => R,
    rs: (_: R) => S,
  ): S;
  pipe<
    const   A,
    const B = never,
    const C = never,
    const D = never,
    const E = never,
    const F = never,
    const G = never,
    const H = never,
    const I = never,
    const J = never,
    const K = never,
    const L = never,
    const M = never,
    const N = never,
    const O = never,
    const P = never,
    const Q = never,
    const R = never,
    const S = never,
    const T = never,
  >(
    this: A,
    ab: (_: A) => B,
    bc: (_: B) => C,
    cd: (_: C) => D,
    de: (_: D) => E,
    ef: (_: E) => F,
    fg: (_: F) => G,
    gh: (_: G) => H,
    hi: (_: H) => I,
    ij: (_: I) => J,
    jk: (_: J) => K,
    kl: (_: K) => L,
    lm: (_: L) => M,
    mn: (_: M) => N,
    no: (_: N) => O,
    op: (_: O) => P,
    pq: (_: P) => Q,
    qr: (_: Q) => R,
    rs: (_: R) => S,
    st: (_: S) => T,
  ): T;
  pipe<
    const A,
    const B = never,
    const C = never,
    const D = never,
    const E = never,
    const F = never,
    const G = never,
    const H = never,
    const I = never,
    const J = never,
    const K = never,
    const L = never,
    const M = never,
    const N = never,
    const O = never,
    const P = never,
    const Q = never,
    const R = never,
    const S = never,
    const T = never,
    const U = never,
  >(
    this: A,
    ab: (_: A) => B,
    bc: (_: B) => C,
    cd: (_: C) => D,
    de: (_: D) => E,
    ef: (_: E) => F,
    fg: (_: F) => G,
    gh: (_: G) => H,
    hi: (_: H) => I,
    ij: (_: I) => J,
    jk: (_: J) => K,
    kl: (_: K) => L,
    lm: (_: L) => M,
    mn: (_: M) => N,
    no: (_: N) => O,
    op: (_: O) => P,
    pq: (_: P) => Q,
    qr: (_: Q) => R,
    rs: (_: R) => S,
    st: (_: S) => T,
    tu: (_: T) => U,
  ): U;
  pipe<
    const A,
    const B = never,
    const C = never,
    const D = never,
    const E = never,
    const F = never,
    const G = never,
    const H = never,
    const I = never,
    const J = never,
    const K = never,
    const L = never,
    const M = never,
    const N = never,
    const O = never,
    const P = never,
    const Q = never,
    const R = never,
    const S = never,
    const T = never,
    const U = never,
  >(
    this: A,
    ab: (_: A) => B,
    bc: (_: B) => C,
    cd: (_: C) => D,
    de: (_: D) => E,
    ef: (_: E) => F,
    fg: (_: F) => G,
    gh: (_: G) => H,
    hi: (_: H) => I,
    ij: (_: I) => J,
    jk: (_: J) => K,
    kl: (_: K) => L,
    lm: (_: L) => M,
    mn: (_: M) => N,
    no: (_: N) => O,
    op: (_: O) => P,
    pq: (_: P) => Q,
    qr: (_: Q) => R,
    rs: (_: R) => S,
    st: (_: S) => T,
    tu: (_: T) => U,
  ): U;
}

/**
 * @since 2.0.0
 */
export const pipeArguments = <A>(self: A, args: IArguments): unknown => {
  switch (args.length) {
    case 0:
      return self;
    case 1:
      return args[0](self);
    case 2:
      return args[1](args[0](self));
    case 3:
      return args[2](args[1](args[0](self)));
    case 4:
      return args[3](args[2](args[1](args[0](self))));
    case 5:
      return args[4](args[3](args[2](args[1](args[0](self)))));
    case 6:
      return args[5](args[4](args[3](args[2](args[1](args[0](self))))));
    case 7:
      return args[6](
        args[5](args[4](args[3](args[2](args[1](args[0](self)))))),
      );
    case 8:
      return args[7](
        args[6](args[5](args[4](args[3](args[2](args[1](args[0](self))))))),
      );
    case 9:
      return args[8](
        args[7](
          args[6](args[5](args[4](args[3](args[2](args[1](args[0](self))))))),
        ),
      );
    default: {
      let ret = self;
      for (let i = 0, len = args.length; i < len; i++) {
        ret = args[i](ret);
      }
      return ret;
    }
  }
};
